### ISSUE TITLE
Drag to delete dosnt work 

### ISSUE THREAD

**Issue by armisis** [o-marshmallow/PocketCHIP-pocket-home#12]
I have an icon to delete but drag does not work. Also the icon I downloaded for doom dosnt even load. And it is valid.

**Comment by o-marshmallow** [comment]
If there is no icon, you can't drag'n drop it. You only need to press the control key while touching the icon you want to delete, a menu will appear, you can select `Delete`

**Comment by armisis** [comment]
Thank you!
