### ISSUE TITLE
Allow for Bash Environment variables / use default .bashrc

### ISSUE THREAD

**Issue by torch2424** [o-marshmallow/PocketCHIP-pocket-home#13]
Hello, I noticed that icons/commands do not adhere to environment variables passed into the command explicitly, or that are defined in the .bashrc.

[The issue is described in better detail here](https://bbs.nextthing.co/t/pocket-home-marshmallow-edition/6579/851)

Any help would be appreciated, and if I have the time, I may be able to fix this myself with some direction.

Thank you!

**Comment by o-marshmallow** [comment]
For anyone encoutering the issue, the solution has been given here: https://bbs.nextthing.co/t/pocket-home-marshmallow-edition/6579/852?u=marshmallow
