### ISSUE TITLE
Spawning of Defunct Processes

### ISSUE THREAD

**Issue by zwack-am** [o-marshmallow/PocketCHIP-pocket-home#17]
I installed the version from your repo and my pocket chip would have issues in the terminal about running out of processes.  I'm probably unusual in that I am running pocket-home on the Standard Image.  This is because I've added a service to have the CHIP reconfigure itself depending on whether it is running over HDMI, TzaTziffy, or oon the PocketCHIP.  

The defunct processes were caused by the spawning of i2cget by Pocket-Home.  I tracked the error to BatteryMonitor.cpp and have submitted a pull request to replace the guts of that portion of the class with a version written in plain C++

**Comment by o-marshmallow** [comment]
Thank you @zwack-am,
Your pull request has been merged
