### ISSUE TITLE
Cannot launch Pocket-Home error after attempting to calibrate screen

### ISSUE THREAD

**Issue by addie-lombardo** [o-marshmallow/PocketCHIP-pocket-home#18]
I recently installed pocket home and am really enjoying it however I seem to have screwed up the configuration file with a syntax error after attempting to calibrate the screen in which the terminal opened and threw an error and wouldn't return to the quit/return home so I restarted. Will poke around the config file later to upload if I can find it.

**Comment by o-marshmallow** [comment]
Is SSH installed on your PocketCHIP ? If yes, the solution is very simple, you can backup your current config file (which has a syntax error) and restore the default one, thanks to the following commands:
`cp ~/.pocket-home/config.json ~/.pocket-home/config.json.bakup`
`cp /usr/share/pocket-home/config.json ~/.pocket-home/config.json`

**Comment by addie-lombardo** [comment]
Worked like a charm, thank you!
