### ISSUE TITLE
How to build Debian package from source

### ISSUE THREAD

**Issue by AlexHunterCodes** [o-marshmallow/PocketCHIP-pocket-home#8]
I'd prefer not to perform a `make install` and overwrite the official `pocket-home` in a way that can't easily be reversed, and would prefer to build a .deb package from source and install that. I can see there is a `debian` package directory already in there, but I have no idea how to actually run the packager. Could you add a makefile target for it?

**Comment by o-marshmallow** [comment]
Hello @AndrewAlexMac ,

This debian folder (now called debian-OLD) wasn't the one I use indeed. I have just pushed my debian folder. I added new rules to the Makefile: pack and install
The rule pack will only copy the compiled binary and put it in the debian folder whereas install will also install it with dpkg right after

**Comment by AlexHunterCodes** [comment]
Thanks!
